# Generated by Django 4.2.3 on 2023-07-29 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_user',
                'managed': False,
            },
        ),
    ]
