# Generated by Django 4.2.3 on 2023-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('srno', models.IntegerField(db_column='Letter_no',primary_key=True)),
                ('letter_no', models.CharField(db_column='Letter_no',max_length=255)),
                ('signing_date', models.DateField(db_column='Signing_date')),
                ('receiving_date', models.DateField(blank=True, db_column='Receiving_date', null=True)),
                ('received_from', models.CharField(blank=True, db_column='Received_from', max_length=255, null=True)),
                ('subject', models.CharField(blank=True, db_column='Subject', max_length=255, null=True)),
                ('unit_assigned_to', models.CharField(blank=True, db_column='Unit_Assigned_to', max_length=255, null=True)),
                ('letter_assigned_to', models.CharField(blank=True, db_column='Letter_assigned_to', max_length=255, null=True)),
                ('mds_remark', models.TextField(blank=True, db_column='MDs_remark', null=True)),
                ('gms_remark', models.TextField(blank=True, db_column='Gms_remark', null=True)),
                ('deputy_gms_remark', models.TextField(blank=True, db_column='Deputy_GMs_remark', null=True)),
                ('fms_remark', models.TextField(blank=True, db_column='Fms_remark', null=True)),
                ('reply_date', models.DateField(blank=True, db_column='Reply_date', null=True)),
                ('reply_reference', models.CharField(blank=True, db_column='Reply_reference', max_length=255, null=True)),
            ],
            options={
                'db_table': 'letter',
                'managed': False,
            },
        ),
    ]
