# Generated by Django 4.2.3 on 2023-07-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={},
        ),
    ]
