# Generated by Django 4.2.3 on 2023-07-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_alter_letter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'managed': False},
        ),
    ]
